[theme]
base="light"
primaryColor = "#E31279"       # Set primary color (e.g., buttons, sliders)
backgroundColor = "#f2f2f2"    # Background color for the main content area
secondaryBackgroundColor = "#ffffff"  # Background color for sidebar
textColor = "#E31279"          # Default text color
font = "sans serif"
